#! /usr/bin/env bash

DAEMONS="\
    mysqld \
    cloudera-quickstart-init"

if [ -e /var/lib/cloudera-quickstart/.kerberos ]; then
    DAEMONS="${DAEMONS} \
        krb5kdc \
        kadmin"
fi

if [ -e /var/lib/cloudera-quickstart/.cloudera-manager ]; then
    DAEMONS="${DAEMONS} \
        cloudera-scm-server-db \
        cloudera-scb-server \
        cloudera-scm-server-db"
elif [ "$1" = "impala" ]; then
    DAEMONS="${DAEMONS} \
        zookeeper-server \
        hadoop-hdfs-datanode \
        hadoop-hdfs-journalnode \
        hadoop-hdfs-namenode \
        hadoop-hdfs-secondarynamenode \
        hadoop-httpfs \
        hive-metastore \
        hive-server2 \
        spark-history-server \
        hue \
        impala-state-store \
        impala-catalog \
        impala-server"
elif [ "$1" = "spark" ]; then
    DAEMONS="${DAEMONS} \
        zookeeper-server \
        hadoop-hdfs-datanode \
        hadoop-hdfs-journalnode \
        hadoop-hdfs-namenode \
        hadoop-hdfs-secondarynamenode \
        hadoop-httpfs \
        hadoop-mapreduce-historyserver \
        hadoop-yarn-nodemanager \
        hadoop-yarn-resourcemanager \
        hive-metastore \
        hive-server2 \
        spark-history-server \
        hue \
        impala-state-store \
        impala-catalog \
        impala-server"
elif [ "$1" = "hbase" ]; then
    DAEMONS="${DAEMONS} \
        zookeeper-server \
        hadoop-hdfs-datanode \
        hadoop-hdfs-journalnode \
        hadoop-hdfs-namenode \
        hadoop-hdfs-secondarynamenode \
        hadoop-httpfs \
        hadoop-mapreduce-historyserver \
        hadoop-yarn-nodemanager \
        hadoop-yarn-resourcemanager \
        spark-history-server \
        hbase-master \
        hbase-regionserver \
        hue"
else
    DAEMONS="${DAEMONS} \
            zookeeper-server \
        hadoop-hdfs-datanode \
        hadoop-hdfs-journalnode \
        hadoop-hdfs-namenode \
        hadoop-hdfs-secondarynamenode \
        hadoop-httpfs \
        hadoop-mapreduce-historyserver \
        hadoop-yarn-nodemanager \
        hadoop-yarn-resourcemanager \
        hbase-master \
        hive-metastore \
        hive-server2 \
        spark-history-server \
        hbase-regionserver \
        hue \
        impala-state-store \
        impala-catalog \
        impala-server"
fi
#       hbase-rest hbase-thrift  oozie solr-server sqoop2-server  removed


for daemon in ${DAEMONS}; do
    sudo service ${daemon} start
done


if [ "$2" = "alive" ]; then
        while true; do sleep 1000; done
else
        exec bash
fi